FOODTYPE.KEI_DEVICE = "KEI_DEVICE"

local KEI_RPC_NAMESPACE = "TendouKei"

local function ClampConfigNumber(value, fallback, min_value, max_value)
    value = tonumber(value) or fallback
    return math.clamp(value, min_value, max_value)
end

local protocol_slot_hard_max = 7
local protocol_slot_max = ClampConfigNumber(GetModConfigData("KEI_PROTOCOL_SLOT_MAX"), protocol_slot_hard_max, 1, protocol_slot_hard_max)
local protocol_slot_base_initial = 1
local protocol_slot_initial_extra = ClampConfigNumber(GetModConfigData("KEI_PROTOCOL_INITIAL_EXTRA_SLOTS"), 0, 0, protocol_slot_max - protocol_slot_base_initial)
local mini_alice_arrow_mode = ClampConfigNumber(GetModConfigData("KEI_MINI_ALICE_ARROW_MODE"), 1, 1, 4)
local mini_alice_max_pages = ClampConfigNumber(GetModConfigData("KEI_MINI_ALICE_MAX_PAGES"), 7, 1, 7)
local rotor_surveyor_range = 500 -- 旋翼调查仪无人机的最大飞行半径，可直接修改
TUNING.KEI_ANALYSIS_CONSUME_EQUIPMENT = GetModConfigData("KEI_ANALYSIS_CONSUME_EQUIPMENT") == true
TUNING.KEI_ANALYSIS_USE_EQUIPMENT_VISUAL = GetModConfigData("KEI_ANALYSIS_USE_EQUIPMENT_VISUAL") ~= false
TUNING.KEI_VIRTUAL_EQUIPMENT_BUILD_DISCOUNT = GetModConfigData("KEI_VIRTUAL_EQUIPMENT_BUILD_DISCOUNT") ~= false
TUNING.KEI_ALLOW_DATA_COPY = GetModConfigData("KEI_ALLOW_DATA_COPY") ~= false
TUNING.KEI_PROTOCOL_DRAIN_SOUND = GetModConfigData("KEI_PROTOCOL_DRAIN_SOUND") ~= false
TUNING.KEI_VIRTUAL_STAFF_ATTACK_COOLDOWN = 3
TUNING.KEI_BEEQUEEN_PRESTIGE_MODE = "area"
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_DURATION = 5
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_COOLDOWN = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_RANGE = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_DAMAGE = 50
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_TICK = 0.5
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_STABILITY_COST = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_AIM_UPDATE_PERIOD = 0.1

-- 三维
TUNING.KEI_MAX_POWER = 120
TUNING.KEI_MAX_STABILITY = 120
TUNING.KEI_MAX_INTEGRITY = 120
TUNING.KEI_PROTOCOL_STAT_BONUS = 10

-- 协议槽设定
TUNING.KEI_PROTOCOL_SLOT_HARD_MAX = protocol_slot_hard_max -- 协议槽位的硬性最大数量
TUNING.KEI_PROTOCOL_SLOT_BASE_INITIAL = protocol_slot_base_initial -- 基础解锁的协议槽位数
TUNING.KEI_PROTOCOL_SLOT_INITIAL = protocol_slot_base_initial + protocol_slot_initial_extra -- 当前配置中初始拥有的协议槽位数
TUNING.KEI_PROTOCOL_SLOT_MAX = protocol_slot_max -- 协议槽位的最大数量（根据配置）
TUNING.KEI_MINI_ALICE_ARROW_MODE = mini_alice_arrow_mode -- 娇小爱丽丝箭头显示与循环翻页模式
TUNING.KEI_MINI_ALICE_MAX_PAGES = mini_alice_max_pages -- 娇小爱丽丝可通过扩容配方解锁的最大页数
TUNING.KEI_ROTOR_SURVEYOR_RANGE = rotor_surveyor_range -- 旋翼调查仪无人机的最大飞行半径
TUNING.KEI_ROTOR_SIGNAL_RANGE_MAX = 1500
TUNING.KEI_ROTOR_SURVEYOR_SPEED = 3 -- Kei 无人机的基础飞行速度，不读取原版旋翼测绘机参数
TUNING.KEI_ROTOR_MAP_SELECT_DETECTION_RADIUS = 10 -- Kei 无人机地图图标选取半径
-- 客户端负载较高时，允许驾驶心跳短暂延迟；松开按键仍会立即停止。
TUNING.KEI_ROTOR_PILOT_INPUT_TIMEOUT = 0.75
TUNING.KEI_ROTOR_MOBILITY_SPEED_MULT_PER_LEVEL = 1
TUNING.KEI_ROTOR_BATTERY_POWER_MULT_PER_LEVEL = 1
TUNING.KEI_ROTOR_POWER_DRAIN_REDUCTION_PER_LEVEL = 1
TUNING.KEI_ROTOR_UPGRADE_EXPERIENCE_COST = 1000
TUNING.KEI_EXPERIENCE_BASE_MAX = 1000
TUNING.KEI_EXPERIENCE_COST_PER_SLOT = 1000
TUNING.KEI_EXPERIENCE_PACK_AMOUNT = 1000
TUNING.KEI_EXPERIENCE_MAX_PER_EXTRA_SLOT = 1000
TUNING.KEI_EXPERIENCE_DAILY_GAIN = 100
TUNING.KEI_EXPERIENCE_COMBAT_RADIUS = 24
TUNING.KEI_EXPERIENCE_COMBAT_HEALTH_RATIO = 0.1
TUNING.KEI_EXPERIENCE_FULL_DAMAGE_MULT = 2
TUNING.KEI_EXPERIENCE_FULL_ABSORB = 0.5
TUNING.KEI_POTENTIAL_DURATION = 240
TUNING.KEI_POTENTIAL_DAMAGE_MULT = 10
TUNING.KEI_POTENTIAL_ABSORB = 0.99
TUNING.KEI_EXPERIENCE_GATHER_AMOUNT = 20
TUNING.KEI_EXPERIENCE_GATHER_DAILY_CAP = 200
TUNING.KEI_EXPERIENCE_CRAFT_AMOUNT = 20
TUNING.KEI_EXPERIENCE_CRAFT_DAILY_CAP = 200
TUNING.KEI_EXPERIENCE_WORK_AMOUNT = 40
TUNING.KEI_EXPERIENCE_WORK_DAILY_CAP = 200
TUNING.KEI_EXPERIENCE_EAT_AMOUNT = 50
TUNING.KEI_EXPERIENCE_EAT_DAILY_CAP = 200
TUNING.KEI_EXPERIENCE_SLEEP_AMOUNT = 50
TUNING.KEI_EXPERIENCE_SLEEP_DAILY_CAP = 50
TUNING.KEI_EXPERIENCE_CAPTURE_AMOUNT = 25
TUNING.KEI_EXPERIENCE_CAPTURE_DAILY_CAP = 50
TUNING.KEI_EXPERIENCE_PLANT_AMOUNT = 10
TUNING.KEI_EXPERIENCE_PLANT_DAILY_CAP = 50
TUNING.KEI_EXPERIENCE_BLUEPRINT_AMOUNT = 50
TUNING.KEI_EXPERIENCE_BLUEPRINT_DAILY_CAP = 50
TUNING.KEI_TASK_EXPERIENCE_REWARD_BY_RARITY = { [1] = 10, [2] = 25, [3] = 50 }

-- 累计经验能力：心灵手巧。
TUNING.KEI_CRAFTSMANSHIP_EXPERIENCE_THRESHOLD = 2000 -- 激活心灵手巧所需的累计经验值
TUNING.KEI_FARMING_MASTER_EXPERIENCE_STEP = 500 -- 种地高手每增加一级范围所需的累计经验值
TUNING.KEI_ZOOLOGIST_EXPERIENCE_THRESHOLD = 10000 -- 激活动物学家所需的累计经验值
TUNING.KEI_BOTANIST_EXPERIENCE_THRESHOLD = 5000 -- 激活植物学家所需的累计经验值
TUNING.KEI_ECONOMIST_EXPERIENCE_THRESHOLD = 15000 -- 激活经济学家所需的累计经验值
TUNING.KEI_SCRAP_MASTER_EXPERIENCE_THRESHOLD = 20000 -- 激活边角料大师所需的累计经验值
TUNING.KEI_FARMING_MASTER_MAX_RANGE = 12 -- 种地高手的最大植物对话范围
TUNING.KEI_BACKUP_BODY_TOTAL_EXPERIENCE = 1000 -- 解锁备份体能力所需的累计经验值
TUNING.KEI_BACKUP_BODY_REVIVE_EXPERIENCE = 500 -- 作祟备份体复活消耗的当前经验值
TUNING.KEI_BACKUP_BODY_LIFETIME = 30 -- 备份体从生成到开始消失的时间

-- 设计中"普通食物转化电量效率较低"的实现参数。
TUNING.KEI_FOOD_ABSORPTION = 0.2 -- 普通食物转化为电量的效率系数（20%）
TUNING.KEI_BATTERY_RESTORE_PERCENT = 0.33 -- 便携电池回复最大电量的比例
TUNING.KEI_REPAIR_RESTORE_PERCENT = 0.33 -- 修理工具回复最大完整度的比例
TUNING.KEI_MAP_TELEPORT_POWER_COST = 30 -- 地图传送生活协议的单次电量消耗
TUNING.KEI_LIFE_GROWTH_ACCELERATION_RADIUS = 20
TUNING.KEI_LIFE_GROWTH_ACCELERATION_PERIOD = 1
TUNING.KEI_LIFE_GROWTH_ACCELERATION_PER_STACK = 2
TUNING.KEI_LIFE_RIPEN_RADIUS = 30 -- 催熟魔法影响范围
TUNING.KEI_LIFE_RIPEN_MAX_TARGETS = 999 -- 催熟魔法单次最多影响的目标数量
TUNING.KEI_LIFE_FISH_CALL_EXPERIENCE_COST = 50 -- 唤鱼魔法经验消耗
TUNING.KEI_LIFE_FULLMOON_EXPERIENCE_COST = 100 -- 满月魔法经验消耗
TUNING.KEI_LIFE_NEWMOON_EXPERIENCE_COST = 100 -- 新月魔法经验消耗
TUNING.KEI_LIFE_RIPEN_EXPERIENCE_COST = 50 -- 催熟魔法经验消耗
TUNING.KEI_LIFE_WEATHER_EXPERIENCE_COST = 50 -- 晴雨魔法经验消耗
TUNING.KEI_LIFE_DURABILITY_RESTORE_PERIOD = 60
TUNING.KEI_LIFE_DURABILITY_RESTORE_PER_STACK = 0.1
TUNING.KEI_ROTOR_CONTROLLER_MAX_POWER = 240
TUNING.KEI_ROTOR_CONTROLLER_DRAIN_RATE = 1
TUNING.KEI_ROTOR_CONTROLLER_REGEN_RATE = 1
TUNING.KEI_ROTOR_SKILL_EXPERIENCE_COST = 1000
TUNING.KEI_ROTOR_BEAM_RADIUS = 8
TUNING.KEI_ROTOR_BEAM_UPDATE_PERIOD = 0.2
TUNING.KEI_ROTOR_BEAM_DRAIN_RATE = 2
TUNING.KEI_ROTOR_SURVEY_DURATION = 3
TUNING.KEI_ROTOR_SURVEY_PROTOCOL_COOLDOWN = 40 * 60
TUNING.KEI_ROTOR_NATURE_GROW_REMAINING_TIME = 15
TUNING.KEI_ROTOR_FRIENDLY_CLEAR_PERIOD = 5
TUNING.KEI_ROTOR_FRIENDLY_RETALIATION_WINDOW = 1
TUNING.KEI_ROTOR_RESURRECTION_DELAY = 5
TUNING.KEI_ROTOR_RESURRECTION_POWER_COST = 120
TUNING.KEI_ROTOR_HEAL_AMOUNT = 1
TUNING.KEI_ROTOR_STRENGTHEN_DAMAGE_MULT = 1.5
TUNING.KEI_ROTOR_STRENGTHEN_SHIELD_COOLDOWN = 5
TUNING.KEI_ROTOR_CONFINEMENT_SPEED_MULT = 0.5
TUNING.KEI_ROTOR_CONFINEMENT_ANIM_MULT = 0.5
TUNING.KEI_DORMANT_POWER_DRAIN = 1 -- 休眠状态每秒消耗的电量
TUNING.KEI_DORMANT_STABILITY_REGEN = 3 -- 休眠状态每秒恢复的数据稳定性
TUNING.KEI_DORMANT_INTEGRITY_REGEN = 3 -- 休眠状态每秒恢复的机体完整度
TUNING.KEI_DORMANT_BATTERY_CHARGE_RATE = 3 -- 休眠时从薇诺娜发电机获得的每秒充电量
TUNING.KEI_DORMANT_ZERO_POWER_GRACE_TIME = 3 -- 休眠时电量为0后强制退出前的宽限时间

-- 低电量 / 自动修复 / 协议消耗相关数值集中放在 TUNING，方便后续平衡。
TUNING.KEI_LOW_POWER_DAMAGE = 3 -- 低电量时每秒受到的伤害值
TUNING.KEI_SELF_REPAIR_PERIOD = 3 -- 自动修复的周期（秒）
TUNING.KEI_PROTOCOL_DRAIN_PERIOD = 10 -- 协议消耗的周期（秒）
TUNING.KEI_PROTOCOL_DRAIN_AMOUNT = 1 -- 每个周期每个协议消耗的值
TUNING.KEI_PROTOCOL_DRAIN_MAX_PER_PERIOD = 5 -- 协议消耗每个周期的扣除上限

-- 基础属性协议随机范围，百分比属性使用整数百分数表示。
TUNING.KEI_BASIC_ATTRIBUTE_POWER_MAX_MIN = -5
TUNING.KEI_BASIC_ATTRIBUTE_POWER_MAX_MAX = 15
TUNING.KEI_BASIC_ATTRIBUTE_STABILITY_MAX_MIN = -5
TUNING.KEI_BASIC_ATTRIBUTE_STABILITY_MAX_MAX = 15
TUNING.KEI_BASIC_ATTRIBUTE_INTEGRITY_MAX_MIN = -5
TUNING.KEI_BASIC_ATTRIBUTE_INTEGRITY_MAX_MAX = 15
TUNING.KEI_BASIC_ATTRIBUTE_POWER_DRAIN_REDUCTION_MIN = 5
TUNING.KEI_BASIC_ATTRIBUTE_POWER_DRAIN_REDUCTION_MAX = 15
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_DAMAGE_BONUS_MIN = -15
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_DAMAGE_BONUS_MAX = 30
TUNING.KEI_BASIC_ATTRIBUTE_BASE_DAMAGE_BONUS_MIN = -5
TUNING.KEI_BASIC_ATTRIBUTE_BASE_DAMAGE_BONUS_MAX = 10
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_DAMAGE_BONUS_MIN = -10
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_DAMAGE_BONUS_MAX = 20
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_SPEED_BONUS_MIN = -10
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_SPEED_BONUS_MAX = 20
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_DAMAGE_REDUCTION_MIN = 1
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_DAMAGE_REDUCTION_MAX = 3
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_HEALTH_LOSS_REDUCTION_MIN = -1
TUNING.KEI_BASIC_ATTRIBUTE_FIXED_HEALTH_LOSS_REDUCTION_MAX = 2
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_DAMAGE_REDUCTION_MIN = -5
TUNING.KEI_BASIC_ATTRIBUTE_PERCENT_DAMAGE_REDUCTION_MAX = 10
TUNING.KEI_BASIC_ATTRIBUTE_MAX_POWER_DRAIN_REDUCTION = 90
TUNING.KEI_BASIC_ATTRIBUTE_MAX_DAMAGE_REDUCTION = 90
TUNING.KEI_COMBAT_PROTOCOL_MAX_DAMAGE_REDUCTION = 90
TUNING.KEI_ROTOR_FOLLOW_DRAIN_RATE = 2
TUNING.KEI_ALTERGUARDIAN_POWER_REGEN = 10 -- 天体英雄协议每个消耗周期回复的电量

TUNING.KEI_RECORDER_RANGE = 35 -- 数据记录器的作用范围
TUNING.KEI_RECORDER_BOSS_DYNAMIC_UPDATE_PERIOD = 3 -- 记录器 Boss 动态攻防倍率刷新周期
TUNING.KEI_RECORDER_NO_PLAYERS_CHECK_PERIOD = 3 -- 战斗数据记录器无人时自动停止检测间隔
TUNING.KEI_RECORDER_ALTERGUARDIAN_ENLIGHTENMENT_DRAIN_PERIOD = 1 -- 记录器天体英雄启迪值满时的电量扣除间隔
TUNING.KEI_RECORDER_ALTERGUARDIAN_ENLIGHTENMENT_DRAIN_AMOUNT = 10 -- 记录器天体英雄启迪值满时每次扣除的电量
TUNING.KEI_RECORDER_ALTERGUARDIAN_ATTACK_SANITY_AMOUNT = 50 -- 记录器天体英雄攻击玩家时固定回复的 SAN
TUNING.KEI_RECORDER_ALTERGUARDIAN_DAWN_COOLDOWN = 30 -- 记录器天体英雄曙光技能冷却时间
TUNING.KEI_RECORDER_ALTERGUARDIAN_DAWN_FX_SCALE = 1.5 -- 记录器天体英雄曙光档案馆特效缩放倍率
TUNING.KEI_RECORDER_ALTERGUARDIAN_DAWN_FX_DURATION = 4 -- 记录器天体英雄曙光档案馆特效持续时间（原始时长的两倍）
TUNING.KEI_RECORDER_DEERCLOPS_FREEZE_ROAR_COOLDOWN = 10 -- 记录器独眼巨鹿范围冰冻嘶吼冷却时间
TUNING.KEI_RECORDER_DEERCLOPS_FREEZE_ROAR_RANGE = 12 -- 记录器独眼巨鹿范围冰冻嘶吼范围
TUNING.KEI_RECORDER_EYEOFTERROR_GAZE_RANGE = 12 -- 记录器克眼前方禁行范围
TUNING.KEI_RECORDER_EYEOFTERROR_GAZE_HALF_ANGLE = 45 -- 记录器克眼前方禁行半角
TUNING.KEI_RECORDER_BEARGER_BEE_COOLDOWN = 20 -- 记录器熊獾生成蜜蜂的冷却时间
TUNING.KEI_RECORDER_BEARGER_BEE_HEALTH = 100 -- 记录器蜜蜂最大生命值
TUNING.KEI_RECORDER_BEARGER_BEE_COUNT_PER_POINT = 6 -- 每个生成点的记录器蜜蜂数量
TUNING.KEI_RECORDER_BEARGER_BEE_SPAWN_DISTANCE = 20 -- 记录器蜜蜂生成点与熊獾的距离
TUNING.KEI_RECORDER_BEARGER_BEE_HEAL_MULTIPLIER = 10 -- 熊獾进食记录器蜜蜂的生命恢复倍率
TUNING.KEI_RECORDER_MOOSE_VORTEX_COOLDOWN = 60 -- 记录器麋鹿鹅漩涡技能冷却时间
TUNING.KEI_RECORDER_MOOSE_VORTEX_COUNT = 4 -- 每次技能生成的漩涡数量
TUNING.KEI_RECORDER_MOOSE_VORTEX_LIFETIME = 40 -- 记录器麋鹿鹅漩涡存在时间
TUNING.KEI_RECORDER_MOOSE_VORTEX_UPDATE_PERIOD = 0.2 -- 漩涡潮湿和牵引检测间隔
TUNING.KEI_RECORDER_MOOSE_VORTEX_SPAWN_DISTANCE = 16 -- 漩涡与数据记录器的固定距离
TUNING.KEI_RECORDER_MOOSE_VORTEX_RADIUS = 8 -- 漩涡影响范围
TUNING.KEI_RECORDER_MOOSE_VORTEX_SCALE = 0.9 -- 漩涡视觉大小倍率
TUNING.KEI_RECORDER_MOOSE_VORTEX_PULL_SPEED = 1.2 -- 漩涡向心牵引速度
TUNING.KEI_RECORDER_MOOSE_VORTEX_SPIRAL_SPEED = 1.5 -- 漩涡切向牵引速度
TUNING.KEI_RECORDER_MOOSE_VORTEX_CENTER_RADIUS_PERCENT = 0.2 -- 漩涡中心伤害范围占漩涡半径的比例
TUNING.KEI_RECORDER_MOOSE_VORTEX_CENTER_DAMAGE = 2 -- 漩涡中心单次持续伤害
TUNING.KEI_RECORDER_MOOSE_VORTEX_CENTER_DAMAGE_INTERVAL = 0.5 -- 漩涡中心伤害间隔
TUNING.KEI_DEERCLOPS_MIN_TEMPERATURE = 10 -- 独眼巨鹿协议防止过冷时的最低体温
TUNING.KEI_DRAGONFLY_MAX_TEMPERATURE = 60 -- 龙蝇协议防止过热时的最高体温
TUNING.KEI_MALBATROSS_OCEAN_CHECK_PERIOD = 0.25 -- 邪天翁协议水面状态检测周期
TUNING.KEI_MALBATROSS_OCEAN_MOISTURE_INTERVAL = 2 -- 邪天翁协议潮湿度增加间隔
TUNING.KEI_MALBATROSS_OCEAN_MOISTURE_PER_INTERVAL = 1 -- 邪天翁协议每个间隔增加的基础潮湿度
TUNING.KEI_MALBATROSS_OCEAN_MOISTURE_MULT = 2 -- 邪天翁协议水面潮湿度倍率
TUNING.KEI_MALBATROSS_OCEAN_DAMAGE_MULT = 1.5 -- 邪天翁高级协议水面伤害倍率
TUNING.KEI_MALBATROSS_OCEAN_SPEED_MULT = 1.5 -- 邪天翁高级协议水面移动速度倍率
TUNING.KEI_RECORDER_MALBATROSS_SKILL_COOLDOWN = 20 -- 记录器邪天翁海浪技能冷却时间
TUNING.KEI_RECORDER_MALBATROSS_WAVE_UPDATE_PERIOD = 0.05 -- 记录器邪天翁浪花轨迹和碰撞检测间隔
TUNING.KEI_RECORDER_MALBATROSS_WAVE_DAMAGE = 20 -- 记录器邪天翁外射浪花命中角色的伤害
TUNING.KEI_RECORDER_MALBATROSS_CONVERGE_RADIUS = 20 -- 记录器邪天翁汇聚浪花生成距离
TUNING.KEI_RECORDER_MALBATROSS_CONVERGE_INTERVAL = 1.5 -- 记录器邪天翁汇聚浪花生成间隔
TUNING.KEI_RECORDER_MALBATROSS_CONVERGE_WAVE_LAYERS = 5 -- 记录器邪天翁汇聚浪花层数
TUNING.KEI_RECORDER_MALBATROSS_CONVERGE_WAVE_COUNT = 12 -- 记录器邪天翁每波汇聚浪花数量
TUNING.KEI_RECORDER_MALBATROSS_CONVERGE_SPEED = 7 -- 记录器邪天翁汇聚浪花速度
TUNING.KEI_RECORDER_MALBATROSS_RING_DURATION = 10 -- 记录器邪天翁旋转浪花持续时间
TUNING.KEI_RECORDER_MALBATROSS_RING_SPEED = 0.75 -- 记录器邪天翁旋转浪花角速度
TUNING.KEI_RECORDER_MALBATROSS_OUTWARD_WAVE_COUNT = 24 -- 记录器邪天翁外射浪花数量
TUNING.KEI_RECORDER_MALBATROSS_OUTWARD_SPEED = 7 -- 记录器邪天翁外射浪花速度
TUNING.KEI_RECORDER_MALBATROSS_OUTWARD_TRAVEL_DISTANCE = 20 -- 记录器邪天翁外射浪花移动距离
TUNING.KEI_RECORDER_MALBATROSS_OUTWARD_WAVE_LAYERS = 5 -- 记录器邪天翁外射浪花层数
TUNING.KEI_RECORDER_MALBATROSS_OUTWARD_LAYER_INTERVAL = 0.8 -- 记录器邪天翁外射浪花层间隔
TUNING.KEI_RECORDER_MALBATROSS_WAVE_TOUCH_RADIUS = 1.25 -- 记录器邪天翁浪花基础命中半径
TUNING.KEI_EYEOFTERROR_DASH_DISTANCE = 16 -- 克眼协议单次冲锋的最大位移距离
TUNING.KEI_EYEOFTERROR_DASH_COOLDOWN = 1 -- 克眼协议冲锋冷却时间
TUNING.KEI_DAYWALKER_LEAP_DISTANCE = 12 -- 梦魇疯猪协议单次跳劈的最大位移距离
TUNING.KEI_DAYWALKER_LEAP_RADIUS = 4 -- 梦魇疯猪协议跳劈的伤害范围
TUNING.KEI_DAYWALKER_LEAP_DAMAGE_BASE = 150 -- 梦魇疯猪协议跳劈的固定伤害
TUNING.KEI_DAYWALKER_LEAP_DAMAGE_MAXHEALTH_PERCENT = 0.04 -- 梦魇疯猪协议跳劈按目标最大生命值追加的伤害比例
TUNING.KEI_DAYWALKER_LEAP_SLOW_MULT = 0.1 -- 梦魇疯猪协议跳劈命中后的移速倍率
TUNING.KEI_DAYWALKER_LEAP_SLOW_DURATION = 3 -- 梦魇疯猪协议跳劈命中后的减速时间
TUNING.KEI_DAYWALKER_SINKHOLE_DURATION = 0.5 -- 梦魇疯猪协议跳劈留下的坑持续时间
TUNING.KEI_DAYWALKER_LEAP_COOLDOWN = 3 -- 梦魇疯猪协议跳劈冷却时间
TUNING.KEI_DAYWALKER2_ABSORB = 0.25 -- 拾荒疯猪高级协议的伤害吸收比例
TUNING.KEI_RECORDER_DAYWALKER_IMPRISON_COOLDOWN = 60 -- 记录器梦魇疯猪禁锢技能冷却时间
TUNING.KEI_RECORDER_DAYWALKER_IMPRISON_PILLAR_DISTANCE = 9 -- 记录器梦魇疯猪禁锢柱子之间的距离
TUNING.KEI_RECORDER_DAYWALKER_IMPRISON_PLAYER_RADIUS = 12 -- 记录器梦魇疯猪禁锢玩家活动范围半径
TUNING.KEI_MINOTAUR_TENTACLE_CHANCE = 0.30 -- 远古守卫者协议触发暗影触手的概率
TUNING.KEI_MINOTAUR_TENTACLE_COOLDOWN = 0.5 -- 远古守卫者协议生成暗影触手后的内置冷却
TUNING.KEI_MINOTAUR_TENTACLE_LIFETIME = 30 -- 远古守卫者协议生成的暗影触手强制存在时间
TUNING.KEI_MINOTAUR_SHADOW_PRISON_CHANCE = 0.15 -- 远古守卫者协议触发暗影牢笼的概率
TUNING.KEI_STALKER_SHADOWSTRIKE_CHANCE = 0.30 -- 织影者协议触发影袭的概率
TUNING.KEI_STALKER_SHADOWSTRIKE_DAMAGE_MULT = 0.5 -- 影袭造成的额外伤害比例
TUNING.KEI_RECORDER_STALKER_NIGHTMARE_COOLDOWN = 30 -- 记录器织影者梦魇技能冷却时间
TUNING.KEI_KLAUS_SOUL_CHANCE = 0.20 -- 克劳斯协议抽取灵魂并治疗周围单位的概率
TUNING.KEI_KLAUS_ADVANCED_SOUL_COOLDOWN = 0.5 -- 克劳斯高级协议抽魂冷却
TUNING.KEI_KLAUS_ADVANCED_MAX_HEALTH_DAMAGE_PERCENT = 0.01 -- 克劳斯高级协议追加目标最大生命值真实伤害比例
TUNING.KEI_KLAUS_ADVANCED_EXECUTE_HEALTH_PERCENT = 0.05 -- 克劳斯高级协议斩杀生命百分比阈值
TUNING.KEI_RECORDER_KLAUS_HELL_CALL_COOLDOWN = 30 -- 记录器克劳斯地狱呼唤冷却时间
TUNING.KEI_RECORDER_KLAUS_SOUL_LIFETIME = 15 -- 地狱呼唤灵魂自然存在时间
TUNING.KEI_RECORDER_KLAUS_SOUL_MAX_HEALTH = 50 -- 地狱呼唤灵魂生命上限
TUNING.KEI_RECORDER_KLAUS_MINION_MAX_HEALTH = 50 -- 地狱呼唤生成单位生命上限
TUNING.KEI_RECORDER_KLAUS_MINION_DAMAGE = 10 -- 地狱呼唤生成单位每次受伤的固定生命损失
TUNING.KEI_RECORDER_KLAUS_MINION_ATTACK_DAMAGE = 100 -- 地狱呼唤生成单位固定攻击力
TUNING.KEI_RECORDER_KLAUS_SOUL_HEAL_AMOUNT = 25 -- 沃托克斯灵魂对地狱呼唤灵魂的固定治疗量
TUNING.KEI_RECORDER_KLAUS_HELL_CALL_HEALTH_COST = 25 -- 地狱呼唤对竞技场玩家造成的生命值扣除
TUNING.KEI_RECORDER_KLAUS_MINION_LIMIT_PER_PLAYER = 5 -- 每名玩家对应的友方和敌方单位共享上限
TUNING.KEI_RECORDER_KLAUS_SOUL_UPDATE_PERIOD = 0.1 -- 灵魂颜色更新周期
TUNING.KEI_TOADSTOOL_SLEEPBOMB_CHANCE = 0.3 -- 蟾蜍协议触发睡袋的概率
TUNING.KEI_TOADSTOOL_SLEEPBOMB_COOLDOWN = 0.5 -- 蟾蜍协议投掷睡袋后的内置冷却
-- 蜘蛛族群系协议
TUNING.KEI_SPIDER_WARRIOR_WEB_SPEED_MULT = 1.25 -- 蜘蛛战士协议在蛛网上的移速倍率
TUNING.KEI_SPIDER_WEB_SPEED_UPDATE_PERIOD = 0.1 -- 蜘蛛网移速检测周期
TUNING.KEI_SPIDER_DROPPER_WEB_DAMAGE_MULT = 1.5 -- 穴居悬蛛协议在蛛网上的攻击倍率
TUNING.KEI_SPIDER_WEB_DAMAGE_UPDATE_PERIOD = 0.1 -- 蛛网增伤检测周期
TUNING.KEI_SPIDER_HIDER_WEB_ABSORB = 0.5 -- 洞穴蜘蛛协议在蛛网上的减伤比例
TUNING.KEI_SPIDER_WEB_ABSORB_UPDATE_PERIOD = 0.1 -- 蛛网减伤检测周期
TUNING.KEI_SPIDER_SPITTER_SLOW_MULT = 0.5 -- 喷吐蜘蛛协议命中后目标移速倍率
TUNING.KEI_SPIDER_SPITTER_SLOW_DURATION = 10 -- 喷吐蜘蛛协议减速持续时间
TUNING.KEI_SPIDER_SHATTERED_REFLECT_DAMAGE = 25 -- 破碎蜘蛛协议固定反伤
TUNING.KEI_SPIDERQUEEN_WEB_RADIUS = 12 -- 蜘蛛网覆盖半径
TUNING.KEI_SPIDERQUEEN_WEB_SLOW = 0.25 -- 蜘蛛网减速倍率（0.25 = 75%减速）
TUNING.KEI_SPIDERQUEEN_WEB_SCAN_PERIOD = 0.25 -- 蜘蛛网范围扫描周期
TUNING.KEI_SPIDERQUEEN_WEB_ALPHA = 0.25 -- 蜘蛛网特效透明度（数值越高越明显）

-- 水域群系协议
TUNING.KEI_GNARWAIL_WAVE_CHANCE = 0.3 -- 一角鲸协议触发水波冲击的概率
TUNING.KEI_GNARWAIL_WAVE_RADIUS = 4 -- 一角鲸协议水波冲击范围
TUNING.KEI_GNARWAIL_WAVE_DAMAGE = 20 -- 一角鲸协议水波伤害
TUNING.KEI_GNARWAIL_WAVE_WETNESS = 20 -- 一角鲸协议范围打湿量
TUNING.KEI_GNARWAIL_WAVE_COOLDOWN = 0.5 -- 防止高频触发的内置冷却
TUNING.KEI_SHARK_MOISTURE_DAMAGE_RATE = 2 -- 岩石大白鲨协议每抵扣 1 点伤害消耗的潮湿度
TUNING.KEI_GRASSGATOR_HEAL_PERIOD = 3 -- 草鳄鱼协议潮湿自愈周期
TUNING.KEI_GRASSGATOR_HEAL_AMOUNT = 1 -- 草鳄鱼协议每次恢复的机体完整度

-- 发条族群系协议
TUNING.KEI_KNIGHT_SHOCK_DAMAGE = 50 -- 发条骑士协议受击反伤和范围电流伤害
TUNING.KEI_KNIGHT_SHOCK_RADIUS = 3 -- 发条骑士协议范围电流半径
TUNING.KEI_KNIGHT_SHOCK_COOLDOWN = 0.1 -- 发条骑士协议防止同帧多次触发的内置冷却
TUNING.KEI_ROOK_GUARD_SUCCESS_COOLDOWN = 0.5 -- 发条战车协议成功格挡后的冷却
TUNING.KEI_ROOK_GUARD_FAIL_COOLDOWN = 5 -- 发条战车协议未格挡到攻击后的冷却
TUNING.KEI_ROOK_GUARD_HIT_SOUND = "WX_rework/shield/hit" -- 发条战车协议成功格挡时播放的 WX 护盾受击音效

TUNING.KEI_MUTATEDBEARGER_ATTACK_SPEED_MULT = 1.3 -- 装甲熊獾协议攻击速度倍率
TUNING.KEI_VAULT_PILLAR_GUARD_ATTACK_SPEED_MULT = 1.2 -- 远古戍卫塔协议攻击速度倍率
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_COOLDOWN = 20 -- 战争瓦器人协议轨道打击冷却时间
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_MAX_HEALTH_DPS = 0.03 -- 战争瓦器人协议月能灼烧每秒按目标最大生命值计算的比例
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_BONUS_DPS = 50 -- 战争瓦器人协议月能灼烧每秒追加伤害
TUNING.KEI_CELESTIAL_ORB_COUNT = 3 -- 天体后裔协议环绕宝珠数量
TUNING.KEI_CELESTIAL_ORB_RADIUS = 2 -- 天体后裔协议宝珠环绕半径
TUNING.KEI_CELESTIAL_ORB_HEIGHT = 0.5 -- 天体后裔协议宝珠显示高度
TUNING.KEI_CELESTIAL_ORB_IDLE_SPEED = 0.012 -- 天体后裔协议宝珠常态旋转速度
TUNING.KEI_CELESTIAL_ORB_ATTACK_SPEED = 0.22 -- 天体后裔协议宝珠攻击触发后的旋转速度
TUNING.KEI_CELESTIAL_ORB_ACCEL_DURATION = 1.25 -- 天体后裔协议攻击后宝珠加速持续时间
TUNING.KEI_CELESTIAL_ORB_DAMAGE_MULT = 0.5 -- 天体后裔协议追加伤害占本次伤害的比例
TUNING.KEI_CELESTIAL_ORB_HIT_RADIUS = 2 -- 天体后裔协议宝珠命中半径
TUNING.KEI_MUTATEDDEERCLOPS_AURA_RADIUS = 5.5 -- 独眼晶体巨鹿协议寒冷圈半径
TUNING.KEI_MUTATEDDEERCLOPS_AURA_DURATION = 5 -- 独眼晶体巨鹿协议寒冷圈持续时间
TUNING.KEI_MUTATEDDEERCLOPS_AURA_COOLDOWN = 3 -- 独眼晶体巨鹿协议寒冷圈触发冷却
TUNING.KEI_MUTATEDDEERCLOPS_AURA_SLOW_MULT = 0.5 -- 独眼晶体巨鹿协议寒冷圈动画与移速倍率
TUNING.KEI_ANTLION_SANDSPIKE_CHANCE = 0.30 -- 蚁狮协议触发高大沙刺的概率
TUNING.KEI_ANTLION_SANDSPIKE_COOLDOWN = 0.5 -- 蚁狮协议生成沙刺后的内置冷却
TUNING.KEI_ANTLION_SANDSPIKE_VERTEX_DELAY = 8 * FRAMES -- 中心沙刺后，三角形顶点沙刺的延迟
TUNING.KEI_ANTLION_SANDSPIKE_TRIANGLE_RADIUS = 1.6 -- 三个顶点沙刺到目标中心的距离
TUNING.KEI_ANTLION_SANDSPIKE_DAMAGE_RADIUS = 1.1 -- 沙刺的实际命中半径
TUNING.KEI_ANTLION_SANDSPIKE_TALL_DAMAGE = 200 -- 中心高大沙刺的目标伤害
TUNING.KEI_ANTLION_SANDSPIKE_SHORT_DAMAGE = 100 -- 三角顶点小沙刺的目标伤害
TUNING.KEI_RECORDER_ANTLION_CASTLE_HEALTH = 200 -- 记录器蚁狮沙堡生命上限
TUNING.KEI_RECORDER_ANTLION_CASTLE_COUNT = 6 -- 记录器蚁狮沙堡数量
TUNING.KEI_RECORDER_ANTLION_CASTLE_RADIUS = 12 -- 记录器蚁狮沙堡生成半径
TUNING.KEI_RECORDER_ANTLION_WALL_COOLDOWN = 30 -- 记录器蚁狮沙墙技能冷却时间
TUNING.KEI_RECORDER_ANTLION_STORM_UPDATE_PERIOD = 0.5 -- 记录器蚁狮竞技场沙尘暴刷新周期
TUNING.KEI_BEEQUEEN_PANIC_DURATION = 5 -- 蜂后协议威压造成的恐慌持续时间
TUNING.KEI_BEEQUEEN_PANIC_RADIUS = 12 -- 蜂后协议嘶吼领域威压范围
TUNING.KEI_BEEQUEEN_BASIC_PANIC_COOLDOWN = 0.5 -- 蜂后初级协议恐惧攻击者触发冷却
TUNING.KEI_BEEQUEEN_PANIC_COOLDOWN = 3 -- 蜂后协议嘶吼领域触发冷却
TUNING.KEI_RECORDER_BEEGUARD_DAMAGE_REDUCTION = 0.5 -- 记录器嗡嗡蜜蜂的减伤比例
TUNING.KEI_RECORDER_BEEGUARD_DAMAGE = 1 -- 记录器嗡嗡蜜蜂的攻击力
TUNING.KEI_RECORDER_BEEGUARD_TRAIL_DURATION = 240 -- 记录器嗡嗡蜜蜂死亡后绿色蜂蜜尾迹的持续时间
TUNING.KEI_RECORDER_BEEGUARD_TRAIL_RADIUS = 2.5 -- 绿色蜂蜜尾迹的影响半径
TUNING.KEI_RECORDER_BEEGUARD_TRAIL_SPEED_MULT = 0.5 -- 绿色蜂蜜尾迹中的玩家移速倍率
TUNING.KEI_RECORDER_BEEGUARD_TRAIL_DAMAGE_INTERVAL = 1 -- 绿色蜂蜜尾迹的中毒伤害间隔
TUNING.KEI_RECORDER_BEEGUARD_TRAIL_DAMAGE = 10 -- 绿色蜂蜜尾迹每次中毒伤害
TUNING.KEI_RECORDER_DAYWALKER_IMPRISON_BOUNDARY_SOFT_ZONE = 1.5 -- 记录器梦魇疯猪禁锢边界的渐进减速范围

for i = 1, TUNING.KEI_PROTOCOL_SLOT_HARD_MAX do
    EQUIPSLOTS["KEI_PROTOCOL_" .. tostring(i)] = "kei_protocol_" .. tostring(i)
end
