FOODTYPE.KEI_DEVICE = "KEI_DEVICE"

local KEI_RPC_NAMESPACE = "TendouKei"
local protocol_slot_mode = GetModConfigData("KEI_PROTOCOL_SLOT_MODE") or "7_2"
local protocol_slot_settings = {
    ["7_2"] = { max = 7, step = 2 },
    ["4_1"] = { max = 4, step = 1 },
}
local protocol_slot_setting = protocol_slot_settings[protocol_slot_mode] or protocol_slot_settings["7_2"]
TUNING.KEI_ANALYSIS_CONSUME_EQUIPMENT = GetModConfigData("KEI_ANALYSIS_CONSUME_EQUIPMENT") == true
TUNING.KEI_ANALYSIS_USE_EQUIPMENT_VISUAL = GetModConfigData("KEI_ANALYSIS_USE_EQUIPMENT_VISUAL") ~= false
TUNING.KEI_ALLOW_DATA_COPY = GetModConfigData("KEI_ALLOW_DATA_COPY") ~= false
TUNING.KEI_PROTOCOL_DRAIN_SOUND = GetModConfigData("KEI_PROTOCOL_DRAIN_SOUND") ~= false
TUNING.KEI_BEEQUEEN_PRESTIGE_MODE = GetModConfigData("KEI_BEEQUEEN_PRESTIGE_MODE") or "area"
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_DURATION = 5
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_COOLDOWN = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_RANGE = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_DAMAGE = 50
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_TICK = 0.5
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_STABILITY_COST = 10
TUNING.KEI_MUTATEDWARG_FLAMETHROWER_AIM_UPDATE_PERIOD = 0.1


TUNING.KEI_MAX_POWER = 120 -- 最大电量上限
TUNING.KEI_MAX_STABILITY = 120 -- 最大稳定性上限
TUNING.KEI_MAX_INTEGRITY = 120 -- 最大机体完整度上限
TUNING.KEI_PROTOCOL_STAT_BONUS = 20 -- 每完成一次协议槽扩展时三维上限增加的数值

-- 设计中"普通食物转化电量效率较低"的实现参数。
TUNING.KEI_FOOD_ABSORPTION = 0.2 -- 普通食物转化为电量的效率系数（20%）
TUNING.KEI_BATTERY_POWER = 60 -- 电池类物品提供的电量值
TUNING.KEI_REPAIR_VALUE = 50 -- 修复物品恢复的机体完整度
TUNING.KEI_MAP_TELEPORT_POWER_COST = 30 -- 地图传送生活协议的单次电量消耗
TUNING.KEI_LIFE_GROWTH_ACCELERATION_RADIUS = 20
TUNING.KEI_LIFE_GROWTH_ACCELERATION_PERIOD = 1
TUNING.KEI_LIFE_GROWTH_ACCELERATION_PER_STACK = 2
TUNING.KEI_LIFE_DURABILITY_RESTORE_PERIOD = 60
TUNING.KEI_LIFE_DURABILITY_RESTORE_PER_STACK = 0.1
TUNING.KEI_DORMANT_POWER_DRAIN = 1 -- 休眠状态每秒消耗的电量
TUNING.KEI_DORMANT_STABILITY_REGEN = 3 -- 休眠状态每秒恢复的数据稳定性
TUNING.KEI_DORMANT_INTEGRITY_REGEN = 3 -- 休眠状态每秒恢复的机体完整度
TUNING.KEI_DORMANT_BATTERY_CHARGE_RATE = 3 -- 休眠时从薇诺娜发电机获得的每秒充电量
TUNING.KEI_DORMANT_ZERO_POWER_GRACE_TIME = 3 -- 休眠时电量为0后强制退出前的宽限时间

-- 低电量 / 自动修复 / 协议消耗相关数值集中放在 TUNING，方便后续平衡。
TUNING.KEI_LOW_POWER_DAMAGE = 3 -- 低电量时每秒受到的伤害值
TUNING.KEI_SELF_REPAIR_PERIOD = 3 -- 自动修复的周期（秒）
TUNING.KEI_PROTOCOL_DRAIN_PERIOD = 10 -- 协议消耗的周期（秒）
TUNING.KEI_PROTOCOL_DRAIN_AMOUNT = 2 -- 每个周期消耗的协议数量
TUNING.KEI_PROTOCOL_DRAIN_MAX_PER_PERIOD = 10 -- 协议消耗每个周期的扣除上限
TUNING.KEI_ALTERGUARDIAN_POWER_REGEN = 10 -- 天体英雄协议每个消耗周期回复的电量
TUNING.KEI_PROTOCOL_SLOT_HARD_MAX = 7 -- 协议槽位的硬性最大数量
TUNING.KEI_PROTOCOL_SLOT_INITIAL = 1 -- 初始拥有的协议槽位数
TUNING.KEI_PROTOCOL_SLOT_MAX = protocol_slot_setting.max -- 协议槽位的最大数量（根据配置）
TUNING.KEI_PROTOCOL_UNLOCK_STEP = protocol_slot_setting.step -- 每次解锁的协议槽位数（根据配置）
TUNING.KEI_RECORDER_RANGE = 35 -- 数据记录器的作用范围
TUNING.KEI_DEERCLOPS_MIN_TEMPERATURE = 10 -- 独眼巨鹿协议防止过冷时的最低体温
TUNING.KEI_DRAGONFLY_MAX_TEMPERATURE = 60 -- 龙蝇协议防止过热时的最高体温
TUNING.KEI_EYEOFTERROR_DASH_DISTANCE = 16 -- 克眼协议单次冲锋的最大位移距离
TUNING.KEI_EYEOFTERROR_DASH_COOLDOWN = 1 -- 克眼协议冲锋冷却时间
TUNING.KEI_DAYWALKER_LEAP_DISTANCE = 12 -- 梦魇疯猪协议单次跳劈的最大位移距离
TUNING.KEI_DAYWALKER_LEAP_RADIUS = 4 -- 梦魇疯猪协议跳劈的伤害范围
TUNING.KEI_DAYWALKER_LEAP_DAMAGE_BASE = 150 -- 梦魇疯猪协议跳劈的固定伤害
TUNING.KEI_DAYWALKER_LEAP_DAMAGE_MAXHEALTH_PERCENT = 0.04 -- 梦魇疯猪协议跳劈按目标最大生命值追加的伤害比例
TUNING.KEI_DAYWALKER_LEAP_SLOW_MULT = 0.1 -- 梦魇疯猪协议跳劈命中后的移速倍率
TUNING.KEI_DAYWALKER_LEAP_SLOW_DURATION = 3 -- 梦魇疯猪协议跳劈命中后的减速时间
TUNING.KEI_DAYWALKER_SINKHOLE_DURATION = 0.5 -- 梦魇疯猪协议跳劈留下的坑持续时间
TUNING.KEI_DAYWALKER_LEAP_COOLDOWN = 3 -- 梦魇疯猪协议跳劈冷却时间
TUNING.KEI_MINOTAUR_TENTACLE_CHANCE = 0.30 -- 远古守卫者协议触发暗影触手的概率
TUNING.KEI_MINOTAUR_TENTACLE_COOLDOWN = 0.5 -- 远古守卫者协议生成暗影触手后的内置冷却
TUNING.KEI_MINOTAUR_TENTACLE_LIFETIME = 30 -- 远古守卫者协议生成的暗影触手强制存在时间
TUNING.KEI_MINOTAUR_SHADOW_PRISON_CHANCE = 0.15 -- 远古守卫者协议触发暗影牢笼的概率
TUNING.KEI_STALKER_SHADOWSTRIKE_CHANCE = 0.30 -- 织影者协议触发影袭的概率
TUNING.KEI_STALKER_SHADOWSTRIKE_DAMAGE_MULT = 0.5 -- 影袭造成的额外伤害比例
TUNING.KEI_KLAUS_SOUL_CHANCE = 0.20 -- 克劳斯协议抽取灵魂并治疗周围单位的概率
TUNING.KEI_TOADSTOOL_SLEEPBOMB_CHANCE = 0.3 -- 蟾蜍协议触发睡眠炸弹弹药的概率
TUNING.KEI_TOADSTOOL_SLEEPBOMB_COOLDOWN = 0.5 -- 蟾蜍协议投掷睡眠炸弹弹药后的内置冷却
TUNING.KEI_MUTATEDBEARGER_ATTACK_SPEED_MULT = 1.3 -- 装甲熊獾协议攻击速度倍率
TUNING.KEI_VAULT_PILLAR_GUARD_ATTACK_SPEED_MULT = 1.2 -- 远古戍卫塔协议攻击速度倍率
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_COOLDOWN = 20 -- 战争瓦器人协议轨道打击冷却时间
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_MAX_HEALTH_DPS = 0.03 -- 战争瓦器人协议月能灼烧每秒按目标最大生命值计算的比例
TUNING.KEI_WAGBOSS_ORBITAL_STRIKE_BONUS_DPS = 50 -- 战争瓦器人协议月能灼烧每秒追加伤害
TUNING.KEI_CELESTIAL_ORB_COUNT = 3 -- 天体后裔协议环绕宝珠数量
TUNING.KEI_CELESTIAL_ORB_RADIUS = 2.7 -- 天体后裔协议宝珠环绕半径
TUNING.KEI_CELESTIAL_ORB_HEIGHT = 1.35 -- 天体后裔协议宝珠显示高度
TUNING.KEI_CELESTIAL_ORB_IDLE_SPEED = 0.012 -- 天体后裔协议宝珠常态旋转速度
TUNING.KEI_CELESTIAL_ORB_ATTACK_SPEED = 0.22 -- 天体后裔协议宝珠攻击触发后的旋转速度
TUNING.KEI_CELESTIAL_ORB_ACCEL_DURATION = 1.25 -- 天体后裔协议攻击后宝珠加速持续时间
TUNING.KEI_CELESTIAL_ORB_DAMAGE_MULT = 0.5 -- 天体后裔协议追加伤害占本次伤害的比例
TUNING.KEI_CELESTIAL_ORB_HIT_RADIUS = 1.35 -- 天体后裔协议宝珠命中半径
TUNING.KEI_MUTATEDDEERCLOPS_AURA_RADIUS = 5.5 -- 独眼晶体巨鹿协议寒冷圈半径
TUNING.KEI_MUTATEDDEERCLOPS_AURA_DURATION = 5 -- 独眼晶体巨鹿协议寒冷圈持续时间
TUNING.KEI_MUTATEDDEERCLOPS_AURA_COOLDOWN = 3 -- 独眼晶体巨鹿协议寒冷圈触发冷却
TUNING.KEI_MUTATEDDEERCLOPS_AURA_SLOW_MULT = 0.5 -- 独眼晶体巨鹿协议寒冷圈动画与移速倍率
TUNING.KEI_ANTLION_SANDSPIKE_CHANCE = 0.30 -- 蚁狮协议触发高大沙刺的概率
TUNING.KEI_ANTLION_SANDSPIKE_COOLDOWN = 0.5 -- 蚁狮协议生成沙刺后的内置冷却
TUNING.KEI_ANTLION_SANDSPIKE_VERTEX_DELAY = 8 * FRAMES -- 中心沙刺后，三角形顶点沙刺的延迟
TUNING.KEI_ANTLION_SANDSPIKE_TRIANGLE_RADIUS = 1.6 -- 三个顶点沙刺到目标中心的距离
TUNING.KEI_ANTLION_SANDSPIKE_DAMAGE_RADIUS = 1.1 -- 沙刺的实际命中半径
TUNING.KEI_ANTLION_SANDSPIKE_TALL_DAMAGE = 200 -- 中心高大沙刺的目标伤害
TUNING.KEI_ANTLION_SANDSPIKE_SHORT_DAMAGE = 100 -- 三角顶点小沙刺的目标伤害
TUNING.KEI_BEEQUEEN_PANIC_DURATION = 5 -- 蜂后协议威压造成的恐慌持续时间
TUNING.KEI_BEEQUEEN_PANIC_RADIUS = 12 -- 蜂后协议嘶吼领域威压范围
TUNING.KEI_BEEQUEEN_PANIC_COOLDOWN = 3 -- 蜂后协议嘶吼领域触发冷却

-- 头部 / 身体解析协议使用的隐藏虚拟装备槽。
for i = 1, TUNING.KEI_PROTOCOL_SLOT_HARD_MAX do
    EQUIPSLOTS["KEI_PROTOCOL_" .. tostring(i)] = "kei_protocol_" .. tostring(i)
end

